apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xjbh3bnkq-python
  janus-idp.io/tekton: xjbh3bnkq-python
  backstage.io/kubernetes-id: xjbh3bnkq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xjbh3bnkq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
